### ISSUE TITLE
crash on connecting oil to Hyper Coolant Factory

### ISSUE THREAD

**Issue by hippyrandall** [DeltaNedas/vbucks#2]
java.lang.NullPointerException
	at mindustry.world.BlockStorage.acceptLiquid(BlockStorage.java:103)
	at mindustry.world.BlockStorage.tryMoveLiquid(BlockStorage.java:156)
	at mindustry.world.blocks.liquid.Conduit.update(Conduit.java:113)
	at mindustry.entities.type.TileEntity.update(TileEntity.java:324)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:51)
	at mindustry.core.Logic.update(Logic.java:241)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:138)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)

**Comment by deltanedas** [comment]
works fine for me, update your game and vbucks mod
